global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-service'
    static_configs:
      - targets: ['api-service:8081']

  - job_name: 'distribution-service'
    static_configs:
      - targets: ['distribution-service:8082']

  - job_name: 'validation-service'
    static_configs:
      - targets: ['validation-service:8083']