global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # StatsD Exporter
  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd-exporter:9102']

  # API Service (future)
  - job_name: 'api-service'
    static_configs:
      - targets: ['api-service:8081']

  # Distribution Service (future)
  - job_name: 'distribution-service'
    static_configs:
      - targets: ['distribution-service:8082']